# Generated by Django 2.2.4 on 2019-08-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('content_string', models.CharField(max_length=1024, verbose_name='raw_string')),
            ],
            options={
                'verbose_name': 'SearchRecord',
                'verbose_name_plural': 'SearchRecord',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='key')),
                ('language', models.IntegerField(choices=[(0, 'CN'), (1, 'EN'), (2, 'empty')], default=0, verbose_name='language')),
                ('search_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.SearchRecord', verbose_name='search_record')),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Key',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='url')),
                ('original_site', models.CharField(max_length=128, verbose_name='original_site')),
                ('content_article', models.TextField(verbose_name='content_article')),
                ('adopted', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='language')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('pub_data', models.DateTimeField(verbose_name='pub_time')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Key', verbose_name='key_id')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
            },
        ),
    ]
