# Generated by Django 2.2.3 on 2019-08-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (0, 'unknown')], verbose_name='sex')),
                ('profession', models.CharField(max_length=128, verbose_name='profession')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ')),
                ('phone', models.CharField(max_length=128, verbose_name='phone_num')),
                ('status', models.IntegerField(choices=[(0, 'apply'), (1, 'pass'), (2, 'refuse')], default=0, verbose_name='status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='reated_time')),
            ],
            options={
                'verbose_name': 'student_info',
                'verbose_name_plural': 'student_info',
            },
        ),
    ]
